#!/usr/local/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
import markdown
import os, sys

if len(sys.argv) == 3:
    input_path = sys.argv[1]
    dest_dir = sys.argv[2]
else:
    input_path = sys.argv[5]
    dest_dir = sys.argv[4]

extension_configs = {
    'mdx_math': {
        'enable_dollar_delimiter': True,
        },
    # 'codehilite': {
    #     'linenums': True,
    #     }
    }

mkin = open(input_path)
md = markdown.Markdown(extensions = ['codehilite','fenced_code','meta','mdx_math'], 
                       extension_configs = extension_configs,
                       output_format = "html5")
gen_html = md.convert(mkin.read())
md_meta =  md.Meta
# doc_title = md_meta.get('title')[0] # [0] -> converts one element list to string
doc_title = os.path.basename(input_path).split('.')[0]
dest_path = dest_dir + '/'+ doc_title  

output = [ """<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <!-- <link href="white.css" type="text/css" rel="stylesheet" /> -->
    <!-- <link href="default.css" type="text/css" rel="stylesheet" /> -->
    <link href="style.css" type="text/css" rel="stylesheet" />
    <link href="codehilite.css" type="text/css" rel="stylesheet" />
    <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"></script>
    <title>%(title)s</title>
  </head>

<body>
""" % { 'title' : doc_title }
]

output.append( gen_html )

output.append( """

</body>

</html>
""" )

outfile = open(dest_path, 'w')
outfile.write(''.join(output))
outfile.close()

# end
