let mapleader = " "

" Manage plugins
call plug#begin('~/.vim/plugged')

" Add all your plugins here (note older versions of Vundle used Bundle instead of Plugin)
Plug 'jeffkreeftmeijer/neovim-sensible'
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'christoomey/vim-tmux-navigator'
" Plug 'Yggdroot/indentLine'
Plug 'mbbill/undotree'

" Telescope
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.0' }

" Treesitter
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'nvim-treesitter/playground'

" LSP Support
Plug 'neovim/nvim-lspconfig'
Plug 'williamboman/mason.nvim'
Plug 'williamboman/mason-lspconfig.nvim'
Plug 'WhoIsSethDaniel/toggle-lsp-diagnostics.nvim'

" Autocompletion
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-path'
Plug 'saadparwaiz1/cmp_luasnip'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-nvim-lua'

"  Snippets
Plug 'L3MON4D3/LuaSnip'
" Snippet collection (Optional)
Plug 'rafamadriz/friendly-snippets'

Plug 'VonHeikemen/lsp-zero.nvim'

Plug 'ryanoasis/vim-devicons'
Plug 'nvim-tree/nvim-web-devicons'

" Markdown and Latex
" Plug 'lervag/vimtex'
" Plug 'KeitaNakamura/tex-conceal.vim', {'for': 'tex'}
Plug 'vimwiki/vimwiki'
" Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'folke/zen-mode.nvim'
Plug 'preservim/vim-pencil'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install' }


" Commodities
" Dashboard
Plug 'glepnir/dashboard-nvim'
" Smooth scrolling
Plug 'psliwka/vim-smoothie'
" Show key combinations
Plug 'liuchengxu/vim-which-key'

" Color schemes
Plug 'folke/tokyonight.nvim', { 'branch': 'main' }
Plug 'rose-pine/neovim'
Plug 'kristijanhusak/vim-hybrid-material'
Plug 'jnurmine/zenburn'
Plug 'altercation/vim-colors-solarized'
Plug 'morhetz/gruvbox'
Plug 'sainnhe/everforest'
Plug 'sainnhe/gruvbox-material'
Plug 'jacoborus/tender.vim'
Plug 'gosukiwi/vim-atom-dark'

call plug#end()

"split navigations
" nnoremap <C-J> <C-W><C-J>
" nnoremap <C-K> <C-W><C-K>
" nnoremap <C-L> <C-W><C-L>
" nnoremap <C-H> <C-W><C-H>

" Easy navigation between tabs
" This mapping conflicts with jedi vim
" map <Leader>n <Esc>:tabprevious<CR>
map <Leader>u <Esc>:tabprevious<CR>
map <Leader>i <Esc>:tabnext<CR>

" Option to store all the swapfiles in the same directory
set directory=$HOME/.vim/swapfiles/

" set nu
set relativenumber
set encoding=utf-8

" Enable folding
set foldmethod=indent
set foldlevel=99

" map <leader>f za<CR>

" enable syntax highlighting
syntax enable

" show line numbers
set number

" set tabs to have 4 spaces
set ts=4

" indent when moving to the next line while writing code
set autoindent

" expand tabs into spaces
set expandtab

" when using the >> or << commands, shift lines by 4 spaces
set shiftwidth=4

" show a visual line under the cursor's current line
set cursorline

" show the matching part of the pair for [] {} and ()
hi MatchParen ctermbg=blue
set showmatch

" Some useful key combinations
:inoremap jk <Esc>
" :vnoremap jk <Esc>
noremap <Leader>s :update<CR>
noremap <Leader>e :quit<CR>
noremap <Leader>E :qa!<CR>

" Remap keys to easily resize splits as in tmux
nnoremap <C-up> <C-W>+
nnoremap <C-down> <C-W>-
nnoremap <C-left> <C-W><
nnoremap <C-right> <C-W>>

:tnoremap <Esc> <C-\><C-n>

" Sort
vnoremap <Leader>s :sort<CR>

" Easier move of blocks
vnoremap < <gv
vnoremap > >gv

" Make the mouse work
set mouse=a
" Let copy and past to other apps
set clipboard=unnamed

" =======[ Make the 81st column stand out ]===========
highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%81v', 100)

" Option to work properly with tmux
" set term=screen-256color
set termguicolors

" Set the color theme if the terminal supports 256 colors
if &t_Co == 256 || has('gui_running')
    " Set the background to dark, and which scheme to use.
    set background=dark
    " colors tokyonight
    " colors rose-pine
    " colors atom-dark
    " colors everforest
    " colors gruvbox
    colors gruvbox-material
    " colors hybrid_material
    " colors tender
    " colors zenburn  
    "
    " Set the background transparent
    " highlight Normal ctermbg=none
    " highlight NonText ctermbg=none
else
    colors peachpuff
endif


" For conceal markers.
if has('conceal')
      set conceallevel=2 concealcursor=niv
endif

" Highlight all instances of word under cursor, when idle.
" Useful when studying strange source code.
" Type leader<h> to toggle highlighting on/off.
nnoremap <leader>h :if AutoHighlightToggle()<Bar>set hls<Bar>endif<CR>
function! AutoHighlightToggle()
    let @/ = ''
    if exists('#auto_highlight')
        au! auto_highlight
        augroup! auto_highlight
        setl updatetime=4000
        echo 'Highlight current word: off'
        return 0
    else
        augroup auto_highlight
            au!
            au CursorHold * let @/ = '\V\<'.escape(expand('<cword>'), '\').'\>'
        augroup end
        setl updatetime=500
        echo 'Highlight current word: ON'
        return 1
    endif
endfunction

" Powerline options
let g:airline_powerline_fonts = 1

" key shortcut for pastemode
set pastetoggle=<F2>

" Update the highlighting of the last search
nnoremap <leader>l :nohl<CR>

nnoremap <leader>ww :VimwikiIndex<CR>
nnoremap <leader>wp :Vimwiki2HTML<CR>
let g:vimwiki_list = [{'path': '~/codeforces/description_problems/',
                      \ 'syntax': 'markdown', 
                      \ 'ext': '.md',
                      \ 'nested_syntaxes':  {'python': 'python', 'c++': 'cpp'},
                      \ 'custom_wiki2html': '~/bin/markdown_py2'}]

let g:vimwiki_ext2syntax = {'.md': 'markdown',
            \ '.mkd': 'markdown',
            \ '.wiki': 'markdown'}
let g:vimwiki_conceal_pre = 1
let g:vimwiki_folding = 'expr'
" let g:vimwiki_filetypes = ['markdown', 'pandoc']

" function! s:auto_goyo()
"   if &ft == 'markdown'
"     Goyo 80
"   elseif exists('#goyo')
"     let bufnr = bufnr('%')
"     Goyo!
"     execute 'b '.bufnr
"   endif
" endfunction

" augroup goyo_markdown
"   autocmd!
"   autocmd BufNewFile,BufRead * call s:auto_goyo()
" augroup END

" autocmd FileType vimwiki Goyo
" autocmd FileType vimwiki ZenMode

augroup pencil
  autocmd!
  autocmd FileType markdown,mkd call pencil#init()
  autocmd FileType vimwiki,text call pencil#init()
augroup END

" autocmd! User GoyoEnter Limelight
" autocmd! User GoyoLeave Limelight!

" Telescope configuration
" Find files using Telescope command-line sugar.
nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>

" Undotree
nnoremap <leader>u :UndotreeToggle<CR>

let g:mapleader = "\<Space>"
let g:maplocalleader = ','
nnoremap <silent> <leader>      :<c-u>WhichKey '<Space>'<CR>
nnoremap <silent> <localleader> :<c-u>WhichKey  ','<CR>

" Configurations in Lua
lua <<EOF
-- Mason configuration
require("mason").setup({
    PATH = "prepend", -- "skip" seems to cause the spawning error
})

-- Treesitter configuration
require'nvim-treesitter.configs'.setup {
  -- A list of parser names, or "all"
  ensure_installed = { "help", "c", "lua", "rust", "python" },

  -- Install parsers synchronously (only applied to `ensure_installed`)
  sync_install = false,

  -- Automatically install missing parsers when entering buffer
  -- Recommendation: set to false if you don't have `tree-sitter` CLI installed locally
  auto_install = true,

  -- List of parsers to ignore installing (for "all")
  ignore_install = { "markdown", "markdown_inline" },

  ---- If you need to change the installation directory of the parsers (see -> Advanced Setup)
  -- parser_install_dir = "/some/path/to/store/parsers", -- Remember to run vim.opt.runtimepath:append("/some/path/to/store/parsers")!

  highlight = {
    -- `false` will disable the whole extension
    enable = true,

    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },
}

-- LSP-zero configuration
-- Learn the keybindings, see :help lsp-zero-keybindings -- Learn to configure LSP servers, see :help lsp-zero-api-showcase
local lsp = require('lsp-zero')
lsp.preset('recommended')

lsp.set_preferences({
  suggest_lsp_servers = false,
  set_lsp_keymaps = {omit = {'<F2>'}},
  vim.keymap.set('n', '<leader>r', '<cmd>lua vim.lsp.buf.rename()<cr>', opts)
})

lsp.setup()

vim.diagnostic.config({
  virtual_text = true,
  signs = true,
  update_in_insert = false,
  underline = true,
  severity_sort = false,
  float = true,
})

-- Custom snippets
require("luasnip.loaders.from_snipmate").lazy_load()

-- Toggle Diagnostics
require'toggle_lsp_diagnostics'.init()

require('dashboard').setup {
    theme = 'hyper',
    config = {
        week_header = {
            enable = true,
        },
        shortcut = {
            { desc = ' Update', group = '@property', action = 'Lazy update', key = 'u' },
            {
                    desc = ' Files',
                    group = 'Label',
                    action = 'Telescope find_files',
                    key = 'f',
            },
            {
                    desc = ' Apps',
                    group = 'DiagnosticHint',
                    action = 'Telescope app',
                    key = 'a',
            },
            {
                    desc = ' dotfiles',
                    group = 'Number',
                    action = 'Telescope dotfiles',
                    key = 'd',
            },
        },
    },

    require("zen-mode").setup {
  window = {
    backdrop = 0.95, -- shade the backdrop of the Zen window. Set to 1 to keep the same as Normal
    -- height and width can be:
    -- * an absolute number of cells when > 1
    -- * a percentage of the width / height of the editor when <= 1
    -- * a function that returns the width or the height
    width = 80, -- width of the Zen window
    height = 1, -- height of the Zen window
    -- by default, no options are changed for the Zen window
    -- uncomment any of the options below, or add other vim.wo options you want to apply
    options = {
      signcolumn = "yes", -- disable signcolumn
      number = false, -- disable number column
      relativenumber = false, -- disable relative numbers
      cursorline = false, -- disable cursorline
      cursorcolumn = false, -- disable cursor column
      foldcolumn = "0", -- disable fold column
      list = false, -- disable whitespace characters
    },
  },
  plugins = {
      -- disable some global vim options (vim.o...)
      -- comment the lines to not apply the options
      options = {
          enabled = true,
          ruler = true, -- disables the ruler text in the cmd line area
          showcmd = true, -- disables the command in the last line of the screen
      },
      twilight = { enabled = true }, -- enable to start Twilight when zen mode opens
      gitsigns = { enabled = false }, -- disables git signs
      tmux = { enabled = true }, -- disables the tmux statusline
  },
  -- callback where you can add custom code when the Zen window opens
  on_open = function(win)
    vim.cmd("Limelight")
    vim.cmd("PencilSoft")
  end,
  -- callback where you can add custom code when the Zen window closes
  on_close = function()
    vim.cmd("Limelight!")
    vim.cmd("PencilOff")
  end,

    }
}

EOF
